# Generated by Django 6.0.2 on 2026-05-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_serviceprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='short_desc',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
