# Generated by Django 6.0.2 on 2026-05-11 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicecategory_short_desc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceProvider',
        ),
    ]
