# Generated by Django 6.0.2 on 2026-04-28 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('provider', 'Provider')], default='customer', max_length=20),
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(upload_to='customer')),
                ('age', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('profile_pic', models.ImageField(upload_to='providers')),
                ('service_area', models.CharField(choices=[('AC & Appliance Repair Jobs', 'AC & Appliance Repair Jobs'), ('Electrical Jobs', 'Electrical Jobs'), ('Plumbing Jobs', 'Plumbing Jobs'), ('Painting Jobs', 'Painting Jobs'), ('Gardening Jobs', 'Gardening Jobs')], max_length=120)),
                ('location', models.CharField(max_length=100, null=True)),
                ('verification_ID', models.ImageField(upload_to='providerId')),
                ('experience', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
