# Generated by Django 6.0.2 on 2026-05-10 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_serviceprovider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceProvider',
        ),
    ]
