# Generated by Django 6.0.2 on 2026-05-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_serviceprovider'),
        ('services', '0004_delete_serviceprovider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceproviderprofile',
            name='service_area',
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='availabilty_status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('offline', 'Offline')], default='available', max_length=50),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='service_field',
            field=models.ManyToManyField(related_name='providers', to='services.servicecategory'),
        ),
    ]
