# Generated by Django 6.0.2 on 2026-05-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_serviceproviderprofile_service_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
