# Generated by Django 6.0.2 on 2026-05-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_serviceproviderprofile_average_rating_and_more'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rejected_providers',
            field=models.ManyToManyField(blank=True, null=True, related_name='rejected_bookings', to='accounts.serviceproviderprofile'),
        ),
    ]
