# Generated by Django 6.0.2 on 2026-05-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_serviceproviderprofile_average_rating_and_more'),
        ('bookings', '0003_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='rejected_providers',
            field=models.ManyToManyField(blank=True, related_name='rejected_bookings', to='accounts.serviceproviderprofile'),
        ),
    ]
